version: "3.6"

services:

  db:
    image: postgres:12.1
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    container_name: db
    ports:
      - 5432:5432

  api:
    image: api
    build:
      context: ..
      dockerfile: ./docker/Dockerfile_api
    container_name: api
    depends_on:
      - db
    ports:
      - 8080:8080