FROM golang:1.13.5-alpine3.10

RUN mkdir /app
WORKDIR /app
COPY ./go.mod .
COPY ./go.sum .

RUN go mod download
RUN go get -u github.com/gobuffalo/packr/v2/packr2
COPY . .

RUN chmod +x ./docker/wait_for.sh

WORKDIR cmd/
RUN go build -o ./api/api ./api

WORKDIR migrator/
RUN packr2 build

WORKDIR ..

ENTRYPOINT ["sh", "-c", "../docker/wait_for.sh db:5432 -- ./migrator/migrator -c ../config_api.yaml up && ./api/api -c ../config_api.yaml serve"]